version: '3'
services:
  routerfleet:
    image: abnerdavi/routerfleet:latest
    build:
      context: .

  routerfleet-cron:
    image: abnerdavi/routerfleet-cron:latest
    build:
      context: ./containers/cron
      dockerfile: Dockerfile-cron

  routerfleet-monitoring:
    image: abnerdavi/routerfleet-monitoring:latest
    build:
      context: ./containers/monitoring
      dockerfile: Dockerfile-monitoring

  routerfleet-nginx:
    image: abnerdavi/routerfleet-nginx:latest
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile-nginx
